# Generated by Django 4.1.4 on 2022-12-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image1',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
